apiVersion: apps/v1
kind: Deployment
metadata:
  name: guna-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gunaapp
  template:
    metadata:
      labels:
        app: gunaapp
    spec:
      containers:
      - name: kube-container
        # Replace with your actual ECR Image URI
        image: 045973518289.dkr.ecr.us-east-1.amazonaws.com/guna/app
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ecr-registry-helper  # <--- THIS MUST MATCH THE SECRET NAME
